# Generated by Django 4.2.1 on 2024-05-31 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nav',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Наименование страницы'),
        ),
        migrations.AlterField(
            model_name='nav',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
