# Generated by Django 4.2.1 on 2024-05-31 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_nav_name_alter_nav_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nav',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
