# Generated by Django 4.1.7 on 2023-04-25 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_furniture_chapter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='furniture',
            name='chapter',
            field=models.CharField(choices=[('KITCHEN', 'Кухни'), ('CABINETS', 'Шкафы'), ('BATHROOM', 'Ванные'), ('FURNITURE', 'Мебель'), ('GARDEN_FURNITURE', 'Садовая мебель')], default='KITCHEN', max_length=100, verbose_name='Раздел'),
        ),
    ]
