# Generated by Django 4.2.1 on 2024-05-31 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_page_imgpage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'verbose_name': 'Статичная страница (подпункт)', 'verbose_name_plural': 'Статичные страницы (подпункты)'},
        ),
        migrations.AddField(
            model_name='page',
            name='nav',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.nav'),
        ),
    ]
