# Generated by Django 4.2.1 on 2024-06-01 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_page_options_page_nav'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'verbose_name': 'Статичная страница', 'verbose_name_plural': 'Статичные страницы'},
        ),
    ]
