# Generated by Django 4.1.7 on 2023-04-30 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_furniture_portfolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='furniture',
            name='product',
            field=models.CharField(choices=[('0', 'Нет'), ('1', 'Да')], default='0', max_length=100, verbose_name='Вывести на главную (кухни)'),
        ),
    ]
