# Generated by Django 4.2.1 on 2024-06-01 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_page_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='chapter',
            new_name='chapter_shownav',
        ),
        migrations.AddField(
            model_name='product',
            name='chapter_nav',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.nav'),
        ),
    ]
