# Generated by Django 4.2.1 on 2024-06-01 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_rename_chapter_product_chapter_shownav_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='chapter_nav',
            new_name='nav',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='chapter_shownav',
            new_name='show_nav',
        ),
    ]
