# Generated by Django 4.2.1 on 2024-06-01 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_rename_chapter_nav_product_nav_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='shownav',
            new_name='show_nav',
        ),
    ]
