# Generated by Django 4.1.7 on 2023-04-30 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_slider'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='description_a',
            field=models.CharField(default=0, max_length=150, verbose_name='Текст кнопки'),
            preserve_default=False,
        ),
    ]
