# Generated by Django 4.2.1 on 2024-06-04 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_rename_shownav_page_show_nav'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImgInterior',
        ),
        migrations.DeleteModel(
            name='Interior',
        ),
    ]
