# Generated by Django 4.1.7 on 2023-05-01 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_furniture_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='furniture',
            name='conclusion',
        ),
        migrations.DeleteModel(
            name='Conclusion',
        ),
    ]
