# Generated by Django 4.1.7 on 2023-05-02 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_furniture_conclusion_delete_conclusion'),
    ]

    operations = [
        migrations.AddField(
            model_name='furniture',
            name='avatar',
            field=models.ImageField(default=0, upload_to='images/', verbose_name='Главная картинка'),
            preserve_default=False,
        ),
    ]
