# Generated by Django 4.1.7 on 2023-05-02 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_furniture_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='name_b',
            field=models.CharField(default=0, max_length=150, verbose_name='Продолжение заголовка (жирный)'),
            preserve_default=False,
        ),
    ]
