# Generated by Django 4.1.7 on 2023-05-05 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_slider_name_b'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('price', models.CharField(max_length=200, verbose_name='Цена')),
                ('avatar', models.ImageField(upload_to='images/', verbose_name='Главная картинка')),
                ('image', models.ImageField(upload_to='images/', verbose_name='Картинка для чертежа')),
                ('property_1', models.CharField(max_length=200, verbose_name='Свойство 1')),
                ('value_1', models.CharField(max_length=200, verbose_name='Значение 1')),
                ('property_2', models.CharField(max_length=200, verbose_name='Свойство 2')),
                ('value_2', models.CharField(max_length=200, verbose_name='Значение 2')),
                ('property_3', models.CharField(max_length=200, verbose_name='Свойство 3')),
                ('value_3', models.CharField(max_length=200, verbose_name='Значение 3')),
                ('property_4', models.CharField(max_length=200, verbose_name='Свойство 4')),
                ('value_4', models.CharField(max_length=200, verbose_name='Значение 4')),
                ('property_5', models.CharField(max_length=200, verbose_name='Свойство 5')),
                ('value_5', models.CharField(max_length=200, verbose_name='Значение 5')),
                ('property_6', models.CharField(max_length=200, verbose_name='Свойство 6')),
                ('value_6', models.CharField(max_length=200, verbose_name='Значение 6')),
                ('property_7', models.CharField(max_length=200, verbose_name='Свойство 7')),
                ('value_7', models.CharField(max_length=200, verbose_name='Значение 7')),
                ('property_8', models.CharField(max_length=200, verbose_name='Свойство 8')),
                ('value_8', models.CharField(max_length=200, verbose_name='Значение 8')),
                ('property_9', models.CharField(max_length=200, verbose_name='Свойство 9')),
                ('value_9', models.CharField(max_length=200, verbose_name='Значение 9')),
                ('property_10', models.CharField(max_length=200, verbose_name='Свойство 10')),
                ('value_10', models.CharField(max_length=200, verbose_name='Значение 10')),
                ('chapter', models.CharField(choices=[('KITCHEN', 'Кухни'), ('CABINETS', 'Шкафы'), ('BATHROOM', 'Ванные'), ('FURNITURE', 'Мебель'), ('GARDEN_FURNITURE', 'Садовая мебель'), ('CHANDELIER', 'Люстры'), ('LAMP', 'Светильники'), ('ALARM_SYSTEMS', 'Трековые системы'), ('CEILING_LIGHT', 'Потолочные')], default='KITCHEN', max_length=100, verbose_name='Раздел')),
                ('portfolio', models.CharField(choices=[('0', 'Нет'), ('1', 'Да')], default='0', max_length=100, verbose_name='Вывести на главную (портфолио)')),
                ('product', models.CharField(choices=[('0', 'Нет'), ('1', 'Да')], default='0', max_length=100, verbose_name='Вывести на главную (кухни)')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='Img',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/', verbose_name='Картинка')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.product')),
            ],
        ),
    ]
