# Generated by Django 4.1.7 on 2023-05-06 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_product_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='property_0',
            field=models.CharField(default=0, max_length=200, verbose_name='Свойство 0 (отображающее в разделе)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='value_0',
            field=models.CharField(default=0, max_length=200, verbose_name='Значение 0'),
            preserve_default=False,
        ),
    ]
