# Generated by Django 4.1.7 on 2023-05-06 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.CharField(max_length=200, null=True, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='property_0',
            field=models.CharField(max_length=200, null=True, verbose_name='Свойство 0 (отображающее в разделе)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='property_1',
            field=models.CharField(max_length=200, null=True, verbose_name='Свойство 1'),
        ),
        migrations.AlterField(
            model_name='product',
            name='property_10',
            field=models.CharField(max_length=200, null=True, verbose_name='Свойство 10'),
        ),
        migrations.AlterField(
            model_name='product',
            name='property_2',
            field=models.CharField(max_length=200, null=True, verbose_name='Свойство 2'),
        ),
        migrations.AlterField(
            model_name='product',
            name='property_3',
            field=models.CharField(max_length=200, null=True, verbose_name='Свойство 3'),
        ),
        migrations.AlterField(
            model_name='product',
            name='property_4',
            field=models.CharField(max_length=200, null=True, verbose_name='Свойство 4'),
        ),
        migrations.AlterField(
            model_name='product',
            name='property_5',
            field=models.CharField(max_length=200, null=True, verbose_name='Свойство 5'),
        ),
        migrations.AlterField(
            model_name='product',
            name='property_6',
            field=models.CharField(max_length=200, null=True, verbose_name='Свойство 6'),
        ),
        migrations.AlterField(
            model_name='product',
            name='property_7',
            field=models.CharField(max_length=200, null=True, verbose_name='Свойство 7'),
        ),
        migrations.AlterField(
            model_name='product',
            name='property_8',
            field=models.CharField(max_length=200, null=True, verbose_name='Свойство 8'),
        ),
        migrations.AlterField(
            model_name='product',
            name='property_9',
            field=models.CharField(max_length=200, null=True, verbose_name='Свойство 9'),
        ),
        migrations.AlterField(
            model_name='product',
            name='value_0',
            field=models.CharField(max_length=200, null=True, verbose_name='Значение 0'),
        ),
        migrations.AlterField(
            model_name='product',
            name='value_1',
            field=models.CharField(max_length=200, null=True, verbose_name='Значение 1'),
        ),
        migrations.AlterField(
            model_name='product',
            name='value_10',
            field=models.CharField(max_length=200, null=True, verbose_name='Значение 10'),
        ),
        migrations.AlterField(
            model_name='product',
            name='value_2',
            field=models.CharField(max_length=200, null=True, verbose_name='Значение 2'),
        ),
        migrations.AlterField(
            model_name='product',
            name='value_3',
            field=models.CharField(max_length=200, null=True, verbose_name='Значение 3'),
        ),
        migrations.AlterField(
            model_name='product',
            name='value_4',
            field=models.CharField(max_length=200, null=True, verbose_name='Значение 4'),
        ),
        migrations.AlterField(
            model_name='product',
            name='value_5',
            field=models.CharField(max_length=200, null=True, verbose_name='Значение 5'),
        ),
        migrations.AlterField(
            model_name='product',
            name='value_6',
            field=models.CharField(max_length=200, null=True, verbose_name='Значение 6'),
        ),
        migrations.AlterField(
            model_name='product',
            name='value_7',
            field=models.CharField(max_length=200, null=True, verbose_name='Значение 7'),
        ),
        migrations.AlterField(
            model_name='product',
            name='value_8',
            field=models.CharField(max_length=200, null=True, verbose_name='Значение 8'),
        ),
        migrations.AlterField(
            model_name='product',
            name='value_9',
            field=models.CharField(max_length=200, null=True, verbose_name='Значение 9'),
        ),
    ]
