# Generated by Django 4.1.7 on 2023-05-11 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_product_date_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='date_added',
        ),
    ]
