# Generated by Django 4.1.7 on 2023-05-26 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_remove_furniture_coating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='novelty',
            field=models.CharField(choices=[('0', 'Нет'), ('1', 'Да')], default='0', max_length=100, verbose_name='Новинка ?'),
        ),
    ]
