# Generated by Django 4.1.7 on 2023-05-26 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_characteristic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='property',
        ),
        migrations.RemoveField(
            model_name='product',
            name='value',
        ),
        migrations.AddField(
            model_name='product',
            name='value_left',
            field=models.CharField(blank=True, max_length=200, verbose_name='Значение слева'),
        ),
        migrations.AddField(
            model_name='product',
            name='value_right',
            field=models.CharField(blank=True, max_length=200, verbose_name='Значение справа'),
        ),
    ]
