# Generated by Django 4.1.7 on 2023-05-27 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_remove_product_property_remove_product_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='chapter',
            field=models.CharField(choices=[('KITCHEN', 'Кухни'), ('CABINETS', 'Шкафы'), ('BATHROOM', 'Ванные'), ('SOFAS', 'Диваны'), ('GARDEN_FURNITURE', 'Садовая мебель'), ('CHANDELIER', 'Люстры'), ('LAMP', 'Светильники'), ('ALARM_SYSTEMS', 'Трековые системы'), ('CEILING_LIGHT', 'Потолочные')], default='KITCHEN', max_length=100, verbose_name='Раздел'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название товара'),
        ),
    ]
