# Generated by Django 4.1.7 on 2023-05-30 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_rename_product_characteristic_kitchen_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='portfolio_chapter',
        ),
    ]
