# Generated by Django 4.1.7 on 2023-05-30 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_remove_product_portfolio_chapter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.AlterField(
            model_name='characteristic',
            name='kitchen',
            field=models.ForeignKey(blank=True, default='1', on_delete=django.db.models.deletion.CASCADE, to='main.product'),
        ),
    ]
