# Generated by Django 4.1.7 on 2023-05-30 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_rename_product_characteristic_kitchen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characteristic',
            name='kitchen',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='fe', to='main.product'),
        ),
    ]
