# Generated by Django 4.2.1 on 2023-06-04 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0044_alter_characteristic_kitchen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characteristic',
            name='kitchen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.product'),
        ),
    ]
