# Generated by Django 4.2.1 on 2023-06-04 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_alter_characteristic_kitchen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='characteristic',
            old_name='kitchen',
            new_name='product',
        ),
    ]
