# Generated by Django 4.2.1 on 2023-06-04 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0046_rename_kitchen_characteristic_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='characteristic',
            old_name='product',
            new_name='kitchen',
        ),
    ]
